name: 'dbt_coder_sandbox'
version: '1.0.0'

profile: 'sandbox'

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
test-paths: ["tests"]

clean-targets:
  - "target"
  - "dbt_packages"
